name: Build and push docker image

on:
  schedule:
    - cron: '0 3 * * *' # Every day at 3 AM
  workflow_dispatch: # Allows manual triggering of the action

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

jobs:
  build-and-push-docker:
    name: Build and push docker image to dockerhub
    runs-on: ubuntu-latest

    steps:
      - name: Get the latest release version
        id: get_version
        run: |
          latest_version=$(curl -s "https://api.github.com/repos/${{ vars.DOCKERHUB_REPOSITORY }}/releases/latest" | jq -r .tag_name)
          if [[ $latest_version = 'null' ]]; then
            latest_version=$(curl -s "https://api.github.com/repos/${{ vars.DOCKERHUB_REPOSITORY }}/releases" | jq -r 'map(select(.prerelease)) | first | .tag_name')
          fi
          echo "latest_version=$latest_version" >> $GITHUB_ENV
          echo "Latest version: $latest_version"

      - name: Checkout Repository
        if: ${{ env.BRANCH_NAME == 'main' }}
        uses: actions/checkout@v3
        with:
          ref: ${{ env.latest_version }}

      - name: Checkout Repository from dev
        if: ${{ env.BRANCH_NAME != 'main' }}
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_NAME }}

      - name: Get Build Number from Docker Hub
        id: get_build_number
        run: |
          latest_tag=$(curl -s -u "$DOCKERHUB_USERNAME:$DOCKERHUB_PASSWORD" "https://hub.docker.com/v2/repositories/${{ vars.DOCKERHUB_REPOSITORY }}/tags" | jq -r ".results[].name" | grep "_" | sort -r | head -n 1)
          if [ -z "$latest_tag" ]; then
            new_build_number="0001"
          else
            last_build_number=$(echo -e "$latest_tag" | awk -F'_' '{print $2}')
            new_build_number=$(printf "%04d" $((10#$last_build_number + 1)))
          fi
          new_tag="${{ env.latest_version }}_$new_build_number"
          echo "build_number=$new_build_number" >> $GITHUB_ENV
          echo "new_tag=$new_tag" >> $GITHUB_ENV
          echo "New tag: $new_tag"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        if: ${{ env.BRANCH_NAME == 'main' }}
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ vars.DOCKERHUB_REPOSITORY }}:${{ env.new_tag }}
            ${{ vars.DOCKERHUB_REPOSITORY }}:${{ env.latest_version }}
            ${{ vars.DOCKERHUB_REPOSITORY }}:latest

      - name: Build and push to dev
        if: ${{ env.BRANCH_NAME != 'main' }}
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ vars.DOCKERHUB_REPOSITORY }}:dev